### ISSUE TITLE
Metals not closing Bloop and SBT after exit or switch.

### ISSUE THREAD

**Issue by grpvw** [scalameta/metals-vscode#1089]
Metals 1.18
After closing Vs code, bloop and sbt continue to run in the background.
Also, in case of a build server switch to sbt, bloop server continues to run as well.

Expected:
When closing Vscode, all related resources are closed.
When switching between build servers, only the relevant continue to run.

Mac M1, Macos 12.5

**Comment by tgodzik** [comment]
Thanks for raising this! It's directly related to https://github.com/scalameta/metals-feature-requests/issues/129 We need a way of shutting down Bloop after it wasn't used for a while.

**Comment by ColonelPhantom** [comment]
I think the issue is that whether you use Bloop or SBT, the build server does not get killed on exit. I tried switching to SBT given that there seems to be a lot of resistance to auto-killing Bloop, but it still left a big (1.1 GB!) Java process hanging on my memory constrained laptop (8 GB). (Somewhat related: Is it possible to tune SBT to use less memory by e.g. changing some JVM flags? They're probably somewhere, but I couldn't set them from the Metals settings in VSCode.)

Personally I think doing something that might be surprising for Bloop users is fine, as long as it is behind a clearly documented switch. As I don't use Bloop for anything but Metals, I'd personally turn it on to stop Bloop (or SBT) from hogging memory in the background. And someone who does use Bloop for other things, or doesn't know what the switch does, can just leave it on. That way everyone can make their own tradeoffs on their own machines :slightly_smiling_face:
