### ISSUE TITLE
Detect build tool in subfolder of workspace?

### ISSUE THREAD

**Issue by CLGitDev** [scalameta/metals-vscode#114]
I have a workspace containing multiple subfolders, which only one of them is Scala where my build.gradle is located.

Is there a way that I can configure the path/file detection pattern?

**Comment by tgodzik** [comment]
Not currently, we don't check the subdirectories. The workaround would be to open the workspace inside that directory. 

I don't want to add `build.gradle` detection in subfolders, since it's hard to reason about what the main workspace directory actually is and Gradle itself would need to be run there. We will keep the same detection mechanism as the actual build tool.
