### ISSUE TITLE
Missing HTTP proxy settings for Coursier when fetching Metals

### ISSUE THREAD

**Issue by mliarakos** [scalameta/metals-vscode#1497]
**Describe the bug**

Since [v1.30.0](https://github.com/scalameta/metals-vscode/releases/tag/v1.30.0), Coursier fails to fetch Metals when an HTTP proxy is needed.

**To Reproduce**

1. Install v1.30.0 of the extension
1. Configure the `serverProperties` setting with the HTTP proxy, e.g.:
   - `-Dhttps.proxyHost=...`
   - `-Dhttps.proxyPort=...`
1. Trigger the Metals extension install process
2. It fails to fetch Metals with an unknown host exception (due to the missing proxy configuration)

This happens both if Coursier is already present on the PATH and if fetched by the extension.

**Expected behavior**

During the install process Coursier uses the HTTP proxy configuration from the `serverProperties` setting to successfully fetch Metals.

**Screenshots**

None.

**Installation:**

- Operating system: Linux
- VSCode version: 1.87.2
- VSCode extension version: 1.30.3
- Metals version: 1.3.0

**Additional context**

In v1.29.0 and earlier the `fetchMetals` method [includes](https://github.com/scalameta/metals-vscode/blob/v1.29.0/packages/metals-languageclient/src/fetchMetals.ts#L64) the `serverProperties` settings as JVM arguments when invoking the default included Coursier. However, in v1.30.0 and newer [no external settings are included](https://github.com/scalameta/metals-vscode/blob/v1.30.0/packages/metals-languageclient/src/fetchMetals.ts#L24) in the Coursier call to fetch Metals.

I believe the same issue occurs when trying to specify an HTTP proxy using `$JAVA_OPTS` or the `.jvmopts` file. Those options are [included in v1.29.0](https://github.com/scalameta/metals-vscode/blob/v1.29.0/packages/metals-languageclient/src/fetchMetals.ts#L63), but [not in v1.30.0](https://github.com/scalameta/metals-vscode/blob/v1.30.0/packages/metals-languageclient/src/fetchMetals.ts#L24). This is just based on the code, I wasn't using it that way so I didn't test it.

This issue might also be present in v1.29.0 [when using an external copy](https://github.com/scalameta/metals-vscode/blob/v1.29.0/packages/metals-languageclient/src/fetchMetals.ts#L83) of Couriser, but I didn't test that either.

**Search terms**

coursier, proxy

**Comment by tgodzik** [comment]
Thanks for reporting, looks like another issue we need to fix, that should be fairly easy I think. Will take a look!

**Comment by LeUser111** [comment]
I've been encountering this issue with multiple colleagues since version 1.30.0 and with version 1.34.0 the issue is back.

Here are my user settings:

```
"metals.mavenScript": "/usr/bin/mvn",
"metals.sbtScript": "/opt/sbt/bin/sbt",
"metals.javaHome": "/opt/jdk",
"metals.scalafmtConfigPath": "/home/user/.scalafmt.conf",
"metals.scalafixConfigPath": "/home/user/.scalafix.conf",
"metals.ammoniteJvmProperties": [
    "-Dhttps.proxyHost=127.0.0.1",
    "-Dhttps.proxyPort=3128"
],
"metals.bloopJvmProperties": [
    "-Dhttps.proxyHost=127.0.0.1",
    "-Dhttps.proxyPort=3128"
],
"metals.serverProperties": [
    "-Xmx2G",
    "-Dhttps.proxyHost=127.0.0.1",
    "-Dhttps.proxyPort=3128",
    "-Djavax.net.ssl.trustStore=/home/user/.m2/grobCaTrustStore.jks",
    "-Djavax.net.ssl.trustStorePassword=changeit"
],
"metals.customRepositories": [
    "https://nexuss/nexus/repository/public/"
],
"metals.coursierMirror": "https://nexuss/nexus/repository/public/",
```

I have removed any additional environment variables (e.g. JAVA_OPTS) and specific settings (e.g. _~/.bloop/bloop.json_ and _~/.config/coursier/mirror.properties_)  except _~/.config/coursier/credentials.properties_


I've just been running multiple tests removing _~/.cache/coursier/_ each time. Things are working with version 1.29.0, 1.32.0 and 1.33.0 (see attached files). 
Versions 1.30.0, 1.31.0 and 1.34.0 ignore the server settings and the installation fails (see attached files).

There are two anomalies with version the working versions, as well: Bloop fails to start initially, requires explicit 'Import build'. That leads to more dependencies being downloaded. That works, as the build server starts afterwards and metals is fully working. However, the download of the bloop dependencies gets reported as _ERROR_.

One more oddity: I have to specify _-Djavax.net.ssl.trustStore_ for coursier even though the CA certificate has been added to _/opt/jdk_ and any other build tool (maven and sbt) uses the certificte from there...

[metals_log_1.29.0.txt](https://github.com/scalameta/metals-vscode/files/15400343/metals_log_1.29.0.txt)
[metals_log_1.30.0.txt](https://github.com/scalameta/metals-vscode/files/15400894/metals_log_1.30.0.txt)
[metals_log_1.31.0.txt](https://github.com/scalameta/metals-vscode/files/15400898/metals_log_1.31.0.txt)
[metals_log_1.32.0.txt](https://github.com/scalameta/metals-vscode/files/15400903/metals_log_1.32.0.txt)
[metals_log_1_33_0.txt](https://github.com/scalameta/metals-vscode/files/15400905/metals_log_1_33_0.txt)
[metals_log_1.34_0.txt](https://github.com/scalameta/metals-vscode/files/15400911/metals_log_1.34_0.txt)

**Comment by mliarakos** [comment]
@LeUser111 The fix in #1498 was released in [v1.32.0](https://github.com/scalameta/metals-vscode/releases/tag/v1.32.0) and reverted in [v1.34.0](https://github.com/scalameta/metals-vscode/releases/tag/v1.34.0), which explains the changes you're seeing.

@tgodzik Why did it need to be reverted? I can submit a modified PR if needed.

**Comment by tgodzik** [comment]
Looks like we can't add the properties on windows in coursier. Adding back the changes aside from that in https://github.com/scalameta/metals-vscode/pull/1510

I will double check if it works and then will release new version

**Comment by tgodzik** [comment]
This should be now fixed, any chance anyone can confirm? You would need to switch to a prerelease version.

I will also want to check if everything works correctly on windows before doing the release.

**Comment by LeUser111** [comment]
@tgodzik The pre-release version is working :) Thank you for the quick fix and thank you for your work on metals in general! It's coming along really nicely :)

@mliarakos Thanks for the initial fix!

**Comment by tgodzik** [comment]
Thanks for checking! I released an official version, there still might be some issue on Windows though.

**Comment by LeUser111** [comment]
The release version is working fine on several machines for us :) Good luck with Windows!
