### ISSUE TITLE
Offer to automatically download JDK if none was detected

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals-vscode#158]
I am thinking we can do:
- if no JDK is detected offer to download one
- if user agrees we can use https://api.adoptopenjdk.net/
- the jdk will be downloaded to .metals

Additionally we could offer a choice of JDK 8 or 11. This would be a simplified version of what the Java plugin already does.

**Comment by sswistun-vl** [comment]
Ok, I'll take care of it.

**Comment by tgodzik** [comment]
@olafurpg @gabro What do you think - it would be a nice experience for beginners and it is already being done in the Java LSP.

**Comment by olafurpg** [comment]
I think this is a great idea! 

> the jdk will be downloaded to .metals

I'm not sure this is a great approach since it would result in Metals re-downloading Java for every workspace. I've found it easy to  use Jabba for installing JDK consistently on macOS, Linux and Windows https://github.com/shyiko/jabba

You could copy-paste the code from GitHub Action setup-scala https://github.com/olafurpg/setup-scala/blob/2534cd39a12c6412eb0644a248ad8eaad2656fe6/src/install.ts

**Comment by tgodzik** [comment]
Fixed via https://github.com/scalameta/metals-vscode/pull/186
