### ISSUE TITLE
Support launch.json configuration to run and debug Scala code

### ISSUE THREAD

**Issue by ColOfAbRiX** [scalameta/metals-vscode#217]
**Is your feature request related to a problem? Please describe.**
I would like to start Run/Debug of scala not from a Code Lens but from the launch configuration so I can add custom configuration and be more flexible. I also find code lenses not nice and I now need to have them enabled.

**Describe the solution you'd like**
Support a "scala" launch type in launch.json and use it through the debug panel of VSCode

**Describe alternatives you've considered**
I'm not aware of any.

**Comment by tgodzik** [comment]
@alekseiAlefirov is starting to work on this as this is a pretty high priority. Without a configuration people are unable to specify any arguments or properties, so run/debug might be problematic to use for them.

**Comment by ckipp01** [comment]
So I'm not super familiar with DAP stuff, but from looking at it, I think so. My initial thought was that it would be great to reuse some of the logic that @alekseiAlefirov did for the `metals.new-scala-file` and do a similar thing like `metals.launch-config` or something and just offload it to the server. Then let it be in charge of creating it correctly with a base template and passing it to the client. _However_, looking at the link you mentioned in [here](https://github.com/scalameta/coc-metals/issues/80#issuecomment-587581170) it looks like a lot of that stuff is already baked into VS Code, including putting the file in the `.vscode` directory, and having built in completion for whats available etc., so I'm not sure if that would actually be a good idea.

With that all being said, the more we can sync on this the better. I'm pinging @danilbykov as well since it looks like he's taking the charge on this on the `coc-metals` side of stuff.

My naive thoughts are, let's offload anything we can to the server to not have to do all the logic both in the VS Code extension and `coc-metals`. If that's not really possible, then let's make sure we agree on the schema (which I believe is already set in DAP world right?) that we are passing in.

**Comment by tgodzik** [comment]
What needs to be sent to Metals is based on https://github.com/build-server-protocol/build-server-protocol/blob/b4a06bdc649cbb03ddcb457bdf0c76a3e296d376/bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaMainClass.java - so that would the schema in a sense.

Although, you are right, some improvements on the server side will be useful to both vim and VS Code, but most likely the launch config itself will not.

**Comment by ctataryn** [comment]
I know for me, this would be super useful. My application takes command-line arguments. Currently if I want to debug my app, I have to jury-rig `main` and seed it with the `args` I am trying to debug with. Too much risk that I'll then go ahead and inadvertently check-in those jury-rigged options.

**Comment by SkyTrix** [comment]
I saw scalameta/metals#1466 makes it possible to pass args to the program, which is a big improvement. What would the path look like to also support setting environment variables in launch.json? From the PR I understood ScalaMainClass is the main bottleneck, correct?

**Comment by tgodzik** [comment]
@SkyTrix We would need to support it via BSP and later in Bloop. I am not 100% sure how hard it will be to implement. Maybe @marek1840 can say more?

**Comment by tgodzik** [comment]
This is implemented as from v0.8.4, we can follow up with a feature request to add support for the environement variables if needed.

**Comment by ctataryn** [comment]
@tgodzik I just gave this a try, however I am always getting the error:

```
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: C:\src\myproj\myproj\rest\src\main\scala\com\myproj\Main
```

My launch.json entry looks like this:

```
"configurations": [    {
      "type": "scala",
      "request": "launch",
      "name": "MyProj Rest",
      "mainClass": "${workspaceFolder}\\rest\\src\\main\\scala\\com\\myproj\\Main",
      "args": [],
      "jvmOptions": []
    } 
]
```

Do you have an example project somewhere that I could try?

**Comment by tgodzik** [comment]
No need to specify the full path:
```
"configurations": [    {
      "type": "scala",
      "request": "launch",
      "name": "MyProj Rest",
      "mainClass": "com.myproj.Main",
      "args": [],
      "jvmOptions": []
    } 
]
```
should work.

**Comment by nilskp** [comment]
@tgodzik This is great. Will there be a follow-up ticket for env vars?

**Comment by ctataryn** [comment]
@tgodzik OMG, too much context switching between Node and Scala projects for me... Thank you.

One note: Running VSCode from the Windows filesystem works great, however when I tried to launch my project from WSL1, and the project itself exists in the WSL1 filesystem,  Metals now fails with the error:

> Missing configuration directory in c:\home\craig\src\myproj\.bloop.
>   1. Did you run bloop outside of the working directory of your build?
>      If so, change your current directory or point directly to your `.bloop` directory via `--config-dir`.
>   2. Did you forget to generate configuration files for your build?
>      Check the installation instructions https://scalacenter.github.io/bloop/setup
>     

That `c:\home\craig\src\myproj` folder should be `/home/craig/src/myproj`. This used to work fine before and is most likely unrelated to this specific feature as it happens when I simply try to import my build through the Metals extension. I even cleared out the .bloop/.metals folders as well.

Let me know if you want me to open a separate ticket, if there is a way for me to revert back a version of the extension could you let me know? I primarily run my dev environment under WSL1.

**Comment by ctataryn** [comment]
> That `c:\home\craig\src\myproj` folder should be `/home/craig/src/myproj`. This used to work fine before and is most likely unrelated to this specific feature as it happens when I simply try to import my build through the Metals extension. I even cleared out the .bloop/.metals folders as well.
> 
> Let me know if you want me to open a separate ticket, if there is a way for me to revert back a version of the extension could you let me know? I primarily run my dev environment under WSL1.

@tgodzik please ignore this, I rebooted and everything is fine! Sometimes this happens with WSL1. I'm all good now, and the launch configuration is working perfectly.

**Comment by tgodzik** [comment]
> @tgodzik This is great. Will there be a follow-up ticket for env vars?

Planning to open it, just need to figure where it should land.

@ctataryn Cool! Please do report if you encounter any issues.

**Comment by AxelMarquez** [comment]
Is it possible to debug (attach) a running process? If so, how would the configuration look like?

I would like to debug a Lagom application that is started with the command:
`sbt -jvm-debug 5005 runAll`

**Comment by tgodzik** [comment]
Unfortunately not yet, there is a feature request for it here: https://github.com/scalameta/metals-feature-requests/issues/86

Not sure how much work it will require, but might be quite a bit since SBT doesn't yet work with DAP. It would be easier with Bloop, but also might require additional work.

**Comment by DzmitryMikhalap** [comment]
Hi, is it possible to use a class with the entrypoint from the external reference to launch the app?

```
"configurations": [
       {
           "type": "scala",
           "name": "Run App",
           "request": "launch",
           "mainClass": "external.Runner",
           "args": []
       }
   ]
```

Get the ClassNotFoundException for this configuration:
```
Caused by: java.lang.ClassNotFoundException: external.Runner
	at scala.meta.internal.metals.BuildTargetClassesFinder.$anonfun$findClassAndBuildTarget$1(BuildTargetClassesFinder.scala:62)
	at scala.Option.fold(Option.scala:251)
	at scala.meta.internal.metals.BuildTargetClassesFinder.findClassAndBuildTarget(BuildTargetClassesFinder.scala:63)
	at scala.meta.internal.metals.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:27)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$1(DebugProvider.scala:130)
	at scala.meta.internal.metals.debug.DebugProvider$$anonfun$withRebuildRetry$1.$anonfun$applyOrElse$5(DebugProvider.scala:290)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
```

**Comment by ctataryn** [comment]
@DzmitryMikhalap How is that external class added to your classpath?  sbt?

**Comment by tgodzik** [comment]
There is existing issue for that: https://github.com/scalameta/metals/issues/1667

We currently check only the classes in the workspace.

**Comment by DzmitryMikhalap** [comment]
> @DzmitryMikhalap How is that external class added to your classpath? sbt?

Yes, the reference is in sbt

**Comment by DzmitryMikhalap** [comment]
> There is existing issue for that: [scalameta/metals#1667](https://github.com/scalameta/metals/issues/1667)
> 
> We currently check only the classes in the workspace.

Thank you for the info!

**Comment by tobio** [comment]
> Planning to open it, just need to figure where it should land.
https://github.com/scalameta/metals-vscode/issues/217#issuecomment-619057664

Was there an issue raised somewhere to support env variables within Metals? I can't seem to find anything related.

**Comment by tgodzik** [comment]
@tobio env variables should work currently with the main classes.
