### ISSUE TITLE
Worksheet Output not displayed for expressions inside objects

### ISSUE THREAD

**Issue by DhruvaSambrani** [scalameta/metals-vscode#347]
# Environment
```
Windows 10 ver 2004
VSCode 1.46.1
metals-vscode 1.9.1
```

**To Reproduce** Steps to reproduce the behavior:

1. Create a Project
2. Create a Worksheet in src\main\scala
3. Type code
4. No Output

**Expected behavior**

The output of the code to the right of the code. Is there a shortcut to trigger output?

**Installation:**

- Operating system: Windows 10 ver2004
- VSCode version: 1.46.1
- VSCode extension version: 1.9.1
- Metals version: 0.9.1

**Additional context**

**Search terms**

Windows, Worksheet output, #168, #169, Worksheet shortcut.

**Comment by tgodzik** [comment]
Thanks for reporting! The worksheets should show decorations inside the file just after saving it. It just needs to have an extension of `.worksheet.sc`.

Does "evaluating worksheet" pop up show in the bottom right? Is there anything in `.metals/metals.log` ?

**Comment by DhruvaSambrani** [comment]
Hey @tgodzik! Thanks for the quick reply.
So I just started a Coursera course on Functional Programming and they use IDEA.
I expected the results to be similar to what they had. IDEA seems to give outputs for function definitions and function calls in both the local(inside an `object`) and global scope, whereas vs-code displays only the result of function calls and not during definition, and that too only in the global scope. Is this the expected behavior?

<img width="451" alt="Annotation 2020-07-10 003138" src="https://user-images.githubusercontent.com/44899822/87080419-44248f00-c245-11ea-852e-8700a3973243.png">

Is this discrepancy because IDEA uses an Ammonite worksheet? If so, Ammonite worksheet (`test.sc`) doesn't show any output whatsoever. Should I make a new issue for the Ammonite issue or just update this one?

**Comment by tgodzik** [comment]
This is an expected behaviour, we evaluate any top level statement that you write inside the worksheet. There is no need to put it all in an object, which will not show any output (definition is not supposed to show anything).

You can easily write:
```scala
def halfof(x: Double): Double = x / 2
halfof(4)
```

Ammonite scripts are a separate entity from worksheets, and in Intellij you can use one or the other: https://www.jetbrains.com/help/idea/work-with-scala-worksheet-and-ammonite.html

This is why we have different extensions for both in Metals. Worksheets should be most useful for you, but if you want to read up at some point about Ammonite take a look at https://ammonite.io/ 

If you have any other problems or questions don't hesitate to also reach to us on discord or gitter.

I will close this one as it's working as expected.
