### ISSUE TITLE
Is not detecting the lightbend/kafka-lag-exporter scala version

### ISSUE THREAD

**Issue by robsonpeixoto** [scalameta/metals-vscode#445]
**Describe the bug**

If you open the project https://github.com/lightbend/kafka-lag-exporter it will detect the wrong(2.12.7) scala version:
- https://github.com/lightbend/kafka-lag-exporter/blob/master/build.sbt#L93
- https://github.com/lightbend/kafka-lag-exporter/blob/master/project/Dependencies.scala#L4

**To Reproduce** Steps to reproduce the behavior:

1. Clone the project https://github.com/lightbend/kafka-lag-exporter
2. Open the project
3. See error

**Expected behavior**

A working environment.

**Screenshots**

![image](https://user-images.githubusercontent.com/124390/98867060-b2c06600-244c-11eb-92bd-ce6d2a62faf4.png)

**Installation:**

- Operating system: macOS
- VSCode version: 1.51.1
- VSCode extension version: 1.9.6
- Metals version: 0.9.5

**Additional context**

Some enabled config, but I tried without it.
```jsonc
  "metals.showImplicitArguments": true,
  "metals.showInferredType": true,
  "metals.superMethodLensesEnabled": true,
```

**Comment by kpbochenek** [comment]
![2020-11-11-225419_1245x192_scrot](https://user-images.githubusercontent.com/10478402/98868714-dac1c080-2470-11eb-9487-f59f947541e1.png)

Metals create special 'sub-project' that handles completions/references/etc. of your build.sbt and all files in project/

Your repository uses sbt: https://github.com/lightbend/kafka-lag-exporter/blob/master/project/build.properties
version 1.2.6 which uses scala 2.12.7 that's why you see this error.

This error only causes VSCode not to provide nice support for build.sbt, except build.sbt all your project should be fully supported.

**Comment by robsonpeixoto** [comment]
Are there a workaround? Or will be needed upgrade the sbt version?

**Comment by tgodzik** [comment]
@robsonpeixoto if you want to use the completions/definitions etc in sbt files then you would need to upgrade sbt version. Otherwise, this is fine to use. Every other Scala file should work normally.

**Comment by robsonpeixoto** [comment]
Thanks @tgodzik and @kpbochenek
