### ISSUE TITLE
Override default value for editor.suggestSelection setting to be "first"

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals-vscode#86]
The default behavior in VS Code is to preselect completion items based on what you have selected before. For example, if you select `toString` once then vscode will preselect that method the next time it appears. However, Metals has better understanding of the context of the source code, for example we use type-aware sorting to highlight the most relevant completion items in pattern matching

![Screenshot 2019-03-08 at 13 48 13](https://user-images.githubusercontent.com/1408093/54083998-7eb5a900-432b-11e9-8af8-05d3e635d18a.png)

Related discussion https://github.com/Microsoft/vscode/issues/54203#issuecomment-404797260

The Metals VS Code extension should either 
- automatically set the value of `editor.suggestSelection` to be `"first"` in Scala sources
- highly recommend that users configure this setting when they use Metals for the first time

**Comment by gabro** [comment]
I think prompting the user out of context (e.g. when the extension activates) is useless/bad, because they don't have a good intuition of what the setting does at that point.

A better moment for prompting the user might be when they first use autocompletion, but that's harder to control from the extension site.

For these reasons, I'm leaning towards just doing this automatically, scoping it to Scala. This should be possible in VSCode with:

```js
[scala]: {
  editor.suggestSelection: "first"
} 
```

I think it's safe enough not to be a problem, and it spares the user attention.

**Comment by olafurpg** [comment]
I believe overriding this setting by default for Scala sources is the way to go, the `"first"` setting improves the UX considerably in my experience compared to the VS Code default "intelligent" ordering.

**Comment by jvican** [comment]
I have just changed to the `"first"` setting and I've noticed a significant improvement in the developer experience. The fact that Metals sorts these completions intelligently makes discovering new methods in APIs so much easier.
  
I believe optimizing for the most common completion is generally not the right thing to do because the completions that I use the most are those that I already know by heart. Completions is most useful when it shows members I don't know but are relevant for my call-site.

**Comment by olafurpg** [comment]
Here's one example where the ordering of completions from Metals matters a lot, we sort abstract methods at the top so you can easily see what method to implement next.

![Screenshot 2019-03-14 at 14 05 03](https://user-images.githubusercontent.com/1408093/54422221-45f04800-470e-11e9-81da-f57a4a6ecf1e.png)

**Comment by gabro** [comment]
I've been thinking "wow but my completions are already pretty good!" and it turns out I already had `first` on 😅
